# Database config
DB_USER = "YOUR_DB_USER"
DB_PASSWORD = "YOUR_DB_PASSWORD"
DB_HOST = "YOUR_DB_HOST"
DB_PORT = "YOUR_DB_PORT"
DB_SCHEMA = "YOUR_DB_SCHEMA"

# Tableau Personal Access Token
PAT_NAME = "YOUR_PAT_NAME"
PAT_SECRET = "YOUR_PAT_SECRET"

# Tableau Server Config
TSC_SERVER_URL = "YOUR_TABLEAU_SERVER_URL"
TSC_SITE_NAME = "YOUR_SITE_NAME"
